version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build:prod
  post_build:
    commands:
        # copy the contents of /build to S3
      - aws s3 rm --recursive s3://editage.campaigns.prod/  
      - aws s3 cp --recursive ./dist s3://editage.campaigns.prod/
      - aws cloudfront create-invalidation --distribution-id E3FJLDEAFAUR7V --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist