export const FLAG = {
    "Indian" : "in" ,     
    "American"  : "us",
    "British" : "uk",
    "Belarus" : "by",
    "Portuguese" : "pt",
   "South African" : "za",
    "Canadian" : "cs",
    "Australian" : "au",
    "New Zealander"  : "nz",
    "Cypriot"  : "cy",
    "Irish" : "ie",
    "Austrian"  : "at",
    "Zimbabwean" : "zw",
    "Israeli" : "il",
    "Italian" : "it",
    "Turkish"  : "tm",
    "Italy" : "it",
    "French" : "fr",
    "Ghanaian" : "gh",
    "Polish" : "pl",
    "Nigerian"  : "ng",
    "Scottish" : "gb",
    "Spanish" : "es",
    "Greek" : "gr",
    "Montenegrin" : "me",
    "Macedonia" : "mk",
    "Bulgarian" : "bg"
}